### ISSUE TITLE
Encountered errors when sending request to FastAPI

### ISSUE THREAD

**Issue by drustanyjt** [code-counselors/code-counselors#26]
I had a bunch of errors when trying to interact with the FastAPI app, but this may be due to user error:

### Post Request to /query_case_by_text

Getting no response data when using the UI after uploading one file. Maybe it's not closely related to the text?
![image](https://github.com/code-counselors/code-counselors/assets/110999129/4e144062-ef02-499e-b2a2-a500ccee8fbf)

### Get Request to /query_case_by_case/{case_id}

I uploaded a file, and saw the number 1536 being output on the console. So I sent a request for case_id 1536,
got a 500 Internal Server Error, and the below AttributeError. It could be that 1536 was not in fact an id.

```
AttributeError: 'dict' object has no attribute 'name'                                                   
['case_id', 'case_name', 'file_name', 'file_source', 'summary']                                         
1536
```

### Server Shutting Down

Got some IOWrapper problem when shutting down, not sure if this is a problem.

```
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name=0 mode='r' encoding='UTF-8'>
```

**Comment by minreiseah** [comment]
Not sure where you're seeing the 1536 but a case id looks like a UUID. Refer to #27.
