### ISSUE TITLE
sort outputs by relevance

### ISSUE THREAD

**Issue by drustanyjt** [code-counselors/code-counselors#60]
Currently it is uncleared how the cases/pinpoints are being sent through the list. Since the frontend merely shows the cases in the order they appear in, it might be better to sort these on the backend first

**Comment by minreiseah** [comment]
probably can sort when retrieving from backend by distance

**Comment by minreiseah** [comment]
will be implemented in db.py where requests are made to weaviate.
sample code:
```python
client = weaviate.Client("http://localhost:8080")

result = (
  client.query
  .get("Article", ["title", "url", "wordCount"])
  .with_sort({"path": ["_distance"], "order": "desc" })
  .do()
)
```

ref: https://weaviate.io/developers/weaviate/api/graphql/additional-operators#sorting
